export const questions = [
  {
    question: "What is the oldest town in NC",
    choices: ["Archers Lodge", "New Bern", "Bath", "Washington"],
    answer: "C",
    explanation: "North Carolina's First Town. European settlement near the Pamlico River in the 1690s led to the creation of Bath, North Carolina's first town, in 1705.",
    author: "Heather Laffler",
  },
  {
    question: "Which one of the following agreements does NOT belong to SFRF Revenue Replacement program?",
    choices: ["OSBM-MONTREAT-171", "HHS-175", "YMCA-COOP-001", "DIT-10"],
    answer: "D",
    explanation: "DIT-10 agreement belongs to SFRF_INFRASTRUCTURE program.",
    author: "Yongjun Lei",
  },
  {
    question: "What year did NC recognize Juneteenth as a state holiday?",
    choices: [2000, 2020, 2007, 2021],
    answer: "C",
    explanation: undefined,
    author: "Neil L. Coles",
  },
  {
    question: "What was the last dry county in North Carolina, until 2021?",
    choices: ["Camden County", "Graham County", "Lincoln County", "Transylvania County"],
    answer: "B",
    explanation: "Since 1948, Graham County did not allow alcohol sales until voters in the town of Robbinsville passed a series of referendums in 2021, finally allowing the sale of beer and wine.",
    author: "Jessie Holmes",
  },
  {
    question: "A Raleigh establishment hosts a Guinness Book of World Record for having the most beer on tap, how many do they have? world record",
    choices: [97, 198, 255, 350],
    answer: "D",
    explanation:
      "Raleigh Beer Garden offers the world's largest selection of beers on tap, 350+ beers, even made official by the folks from the Guinness Book of Records. \nThis massive 8,500 square foot venue over 3 levels has tons of outdoor space, a back garden patio and a rooftop bar and an ever changing selection of beers!",
    author: "Erik Miller",
  },
  {
    question: "What is the largest County in NC?",
    choices: ["Mecklenberg", "Wake", "Guilford", "Alamance"],
    answer: "A",
    explanation: undefined,
    author: "Collin Harris, Rita Wortham, Madison Huff, Candace Rheaume",
  },
  {
    question: "How many recipients are there for North Carolina Coronavirus Relief Funds?",
    choices: ["Over 2,000", "Over 3,000", "Over 5,000", "Over 7,000"],
    answer: "A",
    explanation: undefined,
    author: "Collin Harris",
  },
  {
    question: "When was the very first COVID-19 case reported in North Carolina?",
    choices: ["March 1st, 2020", "March 13th, 2020", "March 5th, 2020", "March 3rd, 2020"],
    answer: "D",
    explanation: "The first case of COVID-19 was announced on March 3rd, 2020, after a person from Wake County was exposed to the virus traveling to a Washington State long-term care facility.",
    author: "Jessie Holmes",
  },
  {
    question: "Although many slaves were freed after President Lincoln's Emancipation Proclamation, slaves in which state had to wait two more years, until June 19, 1865 to receive the news?",
    choices: ["Georgia", "Louisiana", "Texas", "Florida"],
    answer: "C",
    explanation: "2,000 Union Troops arrived in Galveston Bay Texas on June 19, 1865 to free more than 250,000 enslaved black people",
    author: "Jamilla Hawkins",
  },
  {
    question: "How many miles is it from our office to the largest natural lake in North Carolina? (looking for closest estimate)",
    choices: [240, 180, 300, 150],
    answer: "B",
    explanation: "googlemaps shows 181 miles from Dobbs building to Lake Mattamuskeet, NC",
    author: "John Leskovec",
  },
  {
    question: "What is the easternmost county in NC?",
    choices: ["Hyde", "Carteret", "Currituck", "Dare"],
    answer: "D",
    explanation: undefined,
    author: "Stephanie McG",
  },
  {
    question: "What is North Carolina's state seashell?",
    choices: ["Whelk", "Scotch bonnet", "Sand dollar", "Limpet"],
    answer: "B",
    explanation: undefined,
    author: "Stephanie McG",
  },
  {
    question: "What month and year did the North Carolina General Assembly authorize the establishment of the NCPRO?",
    choices: ["March 2020", "April 2020", "May 2020", "None of the above"],
    answer: "C",
    explanation: "Session Law 2020-4 was approved 11:45 a.m. this 4th day of May, 2020",
    author: "John Leskovec",
  },
  {
    question: "How much in funds from the US Treasury is NCPRO tasked with overseeing?",
    choices: ["$2 billion", "$2.8 billion", "$3.6 billion", "$1.7 billion"],
    answer: "C",
    explanation: undefined,
    author: "Collin Harris",
  },
  {
    question: "NCPRO is collecting KPI data for SFRF projects? Which measure type is NOT regular type of KPI measures?",
    choices: ["Finance Measure", "Output Measure", "Outcome Measure", "Tracking Measure"],
    answer: "A",
    explanation: "The regular KPI measure types are: Tracking Measure; Output Measure; Outcome Measure.",
    author: "Yongjun Lei",
  },
  {
    question: "How many NC college baseball teams have won a College World Series?",
    choices: [0, 1, 2, 3],
    answer: "B",
    explanation: "Wake forest won in 1955",
    author: "Tommy Clark",
  },
  {
    question: "What is the westernmost county in NC?",
    choices: ["Cherokee", "Swain", "McDowell", "Buncombe"],
    answer: "A",
    explanation: undefined,
    author: "Stephanie McG",
  },
  {
    question: 'One of the many grants NCPRO oversees includes "GEER" (gear), G-E-E-R. What does it stand for?',
    choices: ["Grants for Effective Education Relief", "Governor's Early Education Relief", "Governor's Emergency Education Relief", "Governor's Emergency Economic Relief"],
    answer: "C",
    explanation: undefined,
    author: "Jessie Holmes",
  },
  {
    question: "How many films and television programs have been filmed in NC?",
    choices: ["0-1000", "1001-2000", "2001-3000", "3001-4000"],
    answer: "D",
    explanation:
      "Some 3,000 films and television programs have been made here, beginning in the early 1900s with silent movies that were shot in western North Carolina.. Some well known examples include Forrest Gump, Last of the Mohicans, The Color Purple, Dirty Dancing, Last of the Mohicans, and The Hunger Games",
    author: "Natalie Garrett",
  },
  {
    question: "What is the smallest National Park in U.S.?",
    choices: ["Zion", "Hot Springs", "Yellowstone", "Grand Canyon"],
    answer: "B",
    explanation: "This park is in Arkansas and just 5,550 acres. It could fit into Grand Canyon near 220 times",
    author: "Hank Yang",
  },
  {
    question: "North Carolina is the birthplace of the following soft drink.",
    choices: ["Coca-Cola", "Pepsi-Cola", "Mountain Dew", "NuGrape"],
    answer: "B",
    explanation: "Pepsi-Cola was created in 1893 by a New Bern pharmacist named Caleb Bradham and was originally named Brad's Drink.",
    author: "Joy Darden",
  },
  {
    question: "How many counties are there in NC?",
    choices: [150, 100, 50, 99],
    answer: "B",
    explanation: undefined,
    author: "Collin Harris , Madison Huff, Candace Rheaume, Rita Wortham",
  },
  {
    question: "What group of Zodiac Signs belong to the Fire element?",
    choices: ["Virgo-Capricorn-Taurus", "Gemini-Libra-Aquarius", "Scorpio -Cancer-Pieces", "Aries-Sagittarius- Leo"],
    answer: "D",
    explanation: "Fire — Aries - Leo - Sagittarius",
    author: "Yeiney Luna",
  },
  {
    question: "When was ARPA signed into law?",
    choices: ["April, 11 2021", "February, 11 2021", "March, 11 2021", "January, 11 2021"],
    answer: "C",
    explanation: undefined,
    author: "Collin Harris , Madison Huff, Candace Rheaume, Rita Wortham",
  },
  {
    question: "Which one of the following item IDs is in a payment request type in PANGRAM?",
    choices: [2000052726, 3000255710, 8000015006, 4000036839],
    answer: "B",
    explanation: "All payment request IDs are 10-digit IDs which start with 3000.",
    author: "Yongjun Lei",
  },
  {
    question: "How many Historically Black Colleges and Universities (HBCUs) in North Carolina?",
    choices: [14, 10, 8, 6],
    answer: "B",
    explanation: "The state ranks second in the country with 10 in the state - just behind Alabama who has 14.",
    author: "Tara Fikes",
  },
  {
    question: "How many lighthouses are currently located in NC",
    choices: [3, 5, 7, 10],
    answer: "C",
    explanation: "The seven standing North Carolina Lighthouses: Currituck. Bodie Island. Hatteras. Ocracoke. Cape Lookout. Oak Island. Bald Head Island. Jan 1, 2012",
    author: "Tommy Clark",
  },
  {
    question: "What NC Governor served the longest number of years?",
    choices: ["Zebulon Baird Vance", "Alexander Martin", "James (Jim) Hunt", "James Martin"],
    answer: "C",
    explanation: "James (Jim) Hunt served a record 4 terms as governor of NC from 1977-1985 and 1993 to 2001.",
    author: "Joy Darden",
  },
  {
    question: "What position did Governor Cooper hold prior to office?",
    choices: ["Lieutenant Governor", "Secretary of State", "Attorney General", "Fighter Pilot"],
    answer: "C",
    explanation: undefined,
    author: "Collin Harris, Rita Wortham, Candace Rheaume, Madison Huff",
  },
  {
    question: "Which SFRF project has the highest total adopted budget?",
    choices: ["DOR-275", "DEQ-147", "DIT-06", "DEQ-148"],
    answer: "D",
    explanation: undefined,
    author: "Mikey Bennett",
  },
  {
    question: "The Durham Bulls is the minor league baseball team of what major league team?",
    choices: ["Atlanta Braves", "Washington Nationals", "Tampa Bay Rays", "Texas Rangers"],
    answer: "C",
    explanation: "Although previously affliated with the Atlanta Braves, the team has been affliated with Tampa Bay since 1998.",
    author: "Tara Fikes",
  },
  {
    question: "What small rural town is home to breeding populations of some of the world's rarest and largest waterfowl, featuring over 2,500 birds from around the world in large walk-through aviaries?",
    choices: ["Duck", "Scotland Neck", "Swansboro", "Bald Head Island"],
    answer: "B",
    explanation: "Located in Halifax County, NC and featuring 18 acres of walk-through aviaries and natural wetlands habitats, Sylvan Heights Bird Park offers an interactive and memorable experience with 200 species of rare waterfowl and exotic birds.",
    author: "Brenda Smith",
  },
  {
    question: "The four colleges of the Tobacco Road Rivalry'have how may combined men's NCAA Division I college basketball championships?",
    choices: [15, 13, 18, 11],
    answer: "B",
    explanation: "6- UNC 5-Duke 2- NC State 0- Wake",
    author: "Mikey Bennett",
  },
  {
    question: "As of August 2022, what was the most popular database management system in the world? The name may even be someone who is wise, insightful, and prophetic.",
    choices: ["SQL", "Pangram", "Oracle", "CSV"],
    answer: "C",
    explanation: "Oracle Database is a multi-model database management system commonly used for running online transaction processing (OLTP), data warehousing (DW) and mixed (OLTP & DW) database workloads.",
    author: "Brenda Smith",
  },
  {
    question: "Jim Hunt served how many terms as Governor of North Carolina?",
    choices: ["One", "Two", "Three", "Four"],
    answer: "D",
    explanation: undefined,
    author: "Mikey Bennett",
  },
  {
    question: "Which is the tallest building piercing the Raleigh skyline?",
    choices: ["BB&T (Two Hanover Square)", "Wells Fargo Capital Center", "PNC Plaza", "Archdale Building"],
    answer: "C",
    explanation: "PNC Plaza built in 2008 reaches 538' tall, over 100' taller then its closest competitor the BB&T Building (431').",
    author: "Erik Miller",
  },
  {
    question: "What Zodiac Sign is represented by the Twins?",
    choices: ["Aquarius", "Gemini", "Scorpio", "Libra"],
    answer: "B",
    explanation:
      'In Latin the twins are also known as the Gemini[e] (literally "twins") or Castores,[f] as well as the Tyndaridae[g] or Tyndarids.[h] Pollux asked Zeus to let him share his own immortality with his twin to keep them together, and they were transformed into the constellation Gemini.',
    author: "Yeiney Luna",
  },
  {
    question: "Which of the following is an unallowable activity of SFRF?",
    choices: ["Replace lost public sector revenue", "Provide premium pay for essential workers", "Invest in water, sewer, and broadband infrastructure", "Deposits into pension funds"],
    answer: "D",
    explanation: "Deposits into pension funds are not an allowable use of SFRF. The other three are allowable uses.",
    author: "Joy Darden",
  },
  {
    question: "What is the first sign of the Zodiac.",
    choices: ["Capricorn", "Gemini", "Aries", "Virgo"],
    answer: "C",
    explanation:
      'Aries (♈︎) (Greek: Κριός, romanized: Kriós, Latin for "ram") is the first astrological sign in the zodiac, spanning the first 30 degrees of celestial longitude (0°≤ λ <30°), and originates from the Aries constellation. Under the tropical zodiac, the Sun transits this sign from approximately March 21 to April 19 each year.[2] This time duration is exactly the first month of the Solar Hijri calendar (Arabic Hamal/Persian Farvardin/Pashto Wray).[3]',
    author: "Yeiney Luna",
  },
  {
    question: "Which Guiness Book of World Records can be claimed by North Carolina?",
    choices: ["Hottest Chili Pepper", "Largest Iced Tea", "Largest Gathering of Elvis Impersonators", "Largest Gathering of People Wearing Swim Caps"],
    answer: "C",
    explanation: "2014, NC's Harrah's Cherokee Casino Resort hosted 895 Elvis impersonators.  Hottest Chili Pepper (Smokin Eds Carolina Reaper), Largest collection of swim cap wearers (2049), and largest Iced Tea (2,524 gallons) belong to our neighbor in the south, South Carolina.",
    author: "Erik Miller",
  },
  {
    question: "What is the largest organ in the human body?",
    choices: ["Liver", "Brain", "Heart", "Skin"],
    answer: "D",
    explanation: undefined,
    author: "Shudy Du",
  },
];
// export const questions = [
//   {
//     question: "What small rural town is home to breeding populations of some of the world's rarest and largest waterfowl, featuring over 2,500 birds from around the world in large walk-through aviaries?",
//     choices: ["Duck", "Scotland Neck", "Swansboro", "Bald Head Island"],
//     answer: "B",
//     explanation: "Located in Halifax County, NC and featuring 18 acres of walk-through aviaries and natural wetlands habitats, Sylvan Heights Bird Park offers an interactive and memorable experience with 200 species of rare waterfowl and exotic birds.",
//     author: "Brenda Smith",
//   },
//   {
//     question: "As of August 2022, what was the most popular database management system in the world? The name may even be someone who is wise, insightful, and prophetic.",
//     choices: ["SQL", "Pangram", "Oracle", "CSV"],
//     answer: "C",
//     explanation: "Oracle Database is a multi-model database management system commonly used for running online transaction processing (OLTP), data warehousing (DW) and mixed (OLTP & DW) database workloads.",
//     author: "Brenda Smith",
//   },
//   {
//     question: "What is the smallest National Park in U.S.?",
//     choices: ["Zion", "Hot Springs", "Yellowstone", "Grand Canyon"],
//     answer: "B",
//     explanation: "This park is in Arkansas and just 5,550 acres. It could fit into Grand Canyon near 220 times",
//     author: "Hank Yang",
//   },
//   {
//     question: "Which SFRF project has the highest total adopted budget?",
//     choices: ["DOR-275", "DEQ-147", "DIT-06", "DEQ-148"],
//     answer: "D",
//     explanation:undefined
//     author: "Mikey Bennett",
//   },
//   {
//     question: 'One of the many grants NCPRO oversees includes "GEER" (gear), G-E-E-R. What does it stand for?',
//     choices: ["Grants for Effective Education Relief", "Governor's Early Education Relief", "Governor's Emergency Education Relief", "Governor's Emergency Economic Relief"],
//     answer: "C",
//     explanation:undefined
//     author: "Jessie Holmes",
//   },
//   {
//     question: "What month and year did the North Carolina General Assembly authorize the establishment of the NCPRO?",
//     choices: ["March 2020", "April 2020", "May 2020", "None of the above"],
//     answer: "C",
//     explanation: "Session Law 2020-4 was approved 11:45 a.m. this 4th day of May, 2020",
//     author: "John Leskovec",
//   },
//   {
//     question: "What was the last dry county in North Carolina, until 2021?",
//     choices: ["Camden County", "Graham County", "Lincoln County", "Transylvania County"],
//     answer: "B",
//     explanation: "Since 1948, Graham County did not allow alcohol sales until voters in the town of Robbinsville passed a series of referendums in 2021, finally allowing the sale of beer and wine.",
//     author: "Jessie Holmes",
//   },
//   {
//     question: "How many miles is it from our office to the largest natural lake in North Carolina? (looking for closest estimate)",
//     choices: [240, 180, 300, 150],
//     answer: "B",
//     explanation: "googlemaps shows 181 miles from Dobbs building to Lake Mattamuskeet, NC",
//     author: "John Leskovec",
//   },
//   {
//     question: "When was the very first COVID-19 case reported in North Carolina?",
//     choices: ["March 1st, 2020", "March 13th, 2020", "March 5th, 2020", "March 3rd, 2020"],
//     answer: "D",
//     explanation: "The first case of COVID-19 was announced on March 3rd, 2020, after a person from Wake County was exposed to the virus traveling to a Washington State long-term care facility.",
//     author: "Jessie Holmes",
//   },
//   {
//     question: "What is the largest organ in the human body?",
//     choices: ["Liver", "Brain", "Heart", "Skin"],
//     answer: "D",
//     explanation:undefined
//     author: "Shudy Du",
//   },
//   {
//     question: "How many NC college baseball teams have won a College World Series?",
//     choices: [0, 1, 2, 3],
//     answer: "B",
//     explanation: "Wake forest won in 1955",
//     author: "Tommy Clark",
//   },
//   {
//     question: "How many lighthouses are currently located in NC",
//     choices: [3, 5, 7, 10],
//     answer: "C",
//     explanation: "The seven standing North Carolina Lighthouses: Currituck. Bodie Island. Hatteras. Ocracoke. Cape Lookout. Oak Island. Bald Head Island. Jan 1, 2012",
//     author: "Tommy Clark",
//   },
//   {
//     question: "What is the first sign of the Zodiac.",
//     choices: ["Capricorn", "Gemini", "Aries", "Virgo"],
//     answer: "C",
//     explanation:
//       'Aries (♈︎) (Greek: Κριός, romanized: Kriós, Latin for "ram") is the first astrological sign in the zodiac, spanning the first 30 degrees of celestial longitude (0°≤ λ <30°), and originates from the Aries constellation. Under the tropical zodiac, the Sun transits this sign from approximately March 21 to April 19 each year.[2] This time duration is exactly the first month of the Solar Hijri calendar (Arabic Hamal/Persian Farvardin/Pashto Wray).[3]',
//     author: "Yeiney Luna",
//   },
//   {
//     question: "What Zodiac Sign is represented by the Twins?",
//     choices: ["Aquarius", "Gemini", "Scorpio", "Libra"],
//     answer: "B",
//     explanation:
//       'In Latin the twins are also known as the Gemini[e] (literally "twins") or Castores,[f] as well as the Tyndaridae[g] or Tyndarids.[h] Pollux asked Zeus to let him share his own immortality with his twin to keep them together, and they were transformed into the constellation Gemini.',
//     author: "Yeiney Luna",
//   },
//   {
//     question: "What group of Zodiac Signs belong to the Fire element?",
//     choices: ["Virgo-Capricorn-Taurus", "Gemini-Libra-Aquarius", "Scorpio -Cancer-Pieces", "Aries-Sagittarius- Leo"],
//     answer: "D",
//     explanation: "Fire — Aries - Leo - Sagittarius",
//     author: "Yeiney Luna",
//   },
//   {
//     question: "Which one of the following item IDs is in a payment request type in PANGRAM?",
//     choices: [2000052726, 3000255710, 8000015006, 4000036839],
//     answer: "B",
//     explanation: "All payment request IDs are 10-digit IDs which start with 3000.",
//     author: "Yongjun Lei",
//   },
//   {
//     question: "Jim Hunt served how many terms as Governor of North Carolina?",
//     choices: ["One", "Two", "Three", "Four"],
//     answer: "D",
//     explanation:undefined
//     author: "Mikey Bennett",
//   },
//   {
//     question: "Which is the tallest building piercing the Raleigh skyline?",
//     choices: ["BB&T (Two Hanover Square)", "Wells Fargo Capital Center", "PNC Plaza", "Archdale Building"],
//     answer: "C",
//     explanation: "PNC Plaza built in 2008 reaches 538' tall, over 100' taller then its closest competitor the BB&T Building (431').",
//     author: "Erik Miller",
//   },
//   {
//     question: "A Raleigh establishment hosts a Guinness Book of World Record for having the most beer on tap, how many do they have? world record",
//     choices: [97, 198, 255, 350],
//     answer: "D",
//     explanation:
//       "Raleigh Beer Garden offers the world's largest selection of beers on tap, 350+ beers, even made official by the folks from the Guinness Book of Records. \nThis massive 8,500 square foot venue over 3 levels has tons of outdoor space, a back garden patio and a rooftop bar and an ever changing selection of beers!",
//     author: "Erik Miller",
//   },
//   {
//     question: "What is the oldest town in NC",
//     choices: ["Archers Lodge", "New Bern", "Bath", "Washington"],
//     answer: "C",
//     explanation: "North Carolina's First Town. European settlement near the Pamlico River in the 1690s led to the creation of Bath, North Carolina's first town, in 1705.",
//     author: "Heather Laffler",
//   },
//   {
//     question: `The four colleges of the "Tobacco Road Rivalry" have how may combined men's NCAA Division I college basketball championships?`,
//     choices: [15, 13, 18, 11],
//     answer: "B",
//     explanation: "6- UNC 5-Duke 2- NC State 0- Wake",
//     author: "Mikey Bennett",
//   },
//   {
//     question: "Although many slaves were freed after President Lincoln's Emancipation Proclamation, slaves in which state had to wait two more years, until June 19, 1865 to receive the news?",
//     choices: ["Georgia", "Louisiana", "Texas", "Florida"],
//     answer: "C",
//     explanation: "2,000 Union Troops arrived in Galveston Bay Texas on June 19, 1865 to free more than 250,000 enslaved black people",
//     author: "Jamilla Hawkins",
//   },
//   {
//     question: "Which Guiness Book of World Records can be claimed by North Carolina?",
//     choices: ["Hottest Chili Pepper", "Largest Iced Tea", "Largest Gathering of Elvis Impersonators", "Largest Gathering of People Wearing Swim Caps"],
//     answer: "C",
//     explanation: "2014, NC's Harrah's Cherokee Casino Resort hosted 895 Elvis impersonators.  Hottest Chili Pepper (Smokin Eds Carolina Reaper), Largest collection of swim cap wearers (2049), and largest Iced Tea (2,524 gallons) belong to our neighbor in the south, South Carolina.",
//     author: "Erik Miller",
//   },
//   {
//     question: "The Durham Bulls is the minor league baseball team of what major league team?",
//     choices: ["Atlanta Braves", "Washington Nationals", "Tampa Bay Rays", "Texas Rangers"],
//     answer: "C",
//     explanation: "Although previously affliated with the Atlanta Braves, the team has been affliated with Tampa Bay since 1998.",
//     author: "Tara Fikes",
//   },
//   {
//     question: "How many Historically Black Colleges and Universities (HBCUs) in North Carolina?",
//     choices: [14, 10, 8, 6],
//     answer: "B",
//     explanation: "The state ranks second in the country with 10 in the state - just behind Alabama who has 14.",
//     author: "Tara Fikes",
//   },
//   {
//     question: "What year did NC recognize Juneteenth as a state holiday?",
//     choices: [2000, 2020, 2007, 2021],
//     answer: "C",
//     explanation:undefined
//     author: "Neil L. Coles",
//   },
//   {
//     question: "What NC Governor served the longest number of years?",
//     choices: ["Zebulon Baird Vance", "Alexander Martin", "James (Jim) Hunt", "James Martin"],
//     answer: "C",
//     explanation: "James (Jim) Hunt served a record 4 terms as governor of NC from 1977-1985 and 1993 to 2001.",
//     author: "Joy Darden",
//   },
//   {
//     question: "Which of the following is an unallowable activity of SFRF?",
//     choices: ["Replace lost public sector revenue", "Provide premium pay for essential workers", "Invest in water, sewer, and broadband infrastructure", "Deposits into pension funds"],
//     answer: "D",
//     explanation: "Deposits into pension funds are not an allowable use of SFRF. The other three are allowable uses.",
//     author: "Joy Darden",
//   },
//   {
//     question: "North Carolina is the birthplace of the following soft drink.",
//     choices: ["Coca-Cola", "Pepsi-Cola", "Mountain Dew", "NuGrape"],
//     answer: "B",
//     explanation: "Pepsi-Cola was created in 1893 by a New Bern pharmacist named Caleb Bradham and was originally named Brad's Drink.",
//     author: "Joy Darden",
//   },
//   {
//     question: "Which one of the following agreements does NOT belong to SFRF Revenue Replacement program?",
//     choices: ["OSBM-MONTREAT-171", "HHS-175", "YMCA-COOP-001", "DIT-10"],
//     answer: "D",
//     explanation: "DIT-10 agreement belongs to SFRF_INFRASTRUCTURE program.",
//     author: "Yongjun Lei",
//   },
//   {
//     question: "How much in funds from the US Treasury is NCPRO tasked with overseeing?",
//     choices: ["$2 billion", "$2.8 billion", "$3.6 billion", "$1.7 billion"],
//     answer: "C",
//     explanation:undefined
//     author: "Collin Harris",
//   },
//   {
//     question: "What is North Carolina's state seashell?",
//     choices: ["Whelk", "Scotch bonnet", "Sand dollar", "Limpet"],
//     answer: "B",
//     explanation:undefined
//     author: "Stephanie McG",
//   },
//   {
//     question: "What is the westernmost county in NC?",
//     choices: ["Cherokee", "Swain", "McDowell", "Buncombe"],
//     answer: "A",
//     explanation:undefined
//     author: "Stephanie McG",
//   },
//   {
//     question: "What is the easternmost county in NC?",
//     choices: ["Hyde", "Carteret", "Currituck", "Dare"],
//     answer: "D",
//     explanation:undefined
//     author: "Stephanie McG",
//   },
//   {
//     question: "When was ARPA signed into law?",
//     choices: ["April, 11 2021", "February, 11 2021", "March, 11 2021", "January, 11 2021"],
//     answer: "C",
//     explanation:undefined
//     author: "Collin Harris , Madison Huff, Candace Rheaume, Rita Wortham",
//   },
//   {
//     question: "How many recipients are there for North Carolina Coronavirus Relief Funds?",
//     choices: ["Over 2,000", "Over 3,000", "Over 5,000", "Over 7,000"],
//     answer: "A",
//     explanation:undefined
//     author: "Collin Harris",
//   },
//   {
//     question: "What is the largest County in NC?",
//     choices: ["Mecklenberg", "Wake", "Guilford", "Alamance"],
//     answer: "A",
//     explanation:undefined
//     author: "Collin Harris, Rita Wortham, Madison Huff, Candace Rheaume",
//   },
//   {
//     question: "How many counties are there in NC?",
//     choices: [150, 100, 50, 99],
//     answer: "B",
//     explanation:undefined
//     author: "Collin Harris , Madison Huff, Candace Rheaume, Rita Wortham",
//   },
//   {
//     question: "What position did Governor Cooper hold prior to office?",
//     choices: ["Lieutenant Governor", "Secretary of State", "Attorney General", "Fighter Pilot"],
//     answer: "C",
//     explanation:undefined
//     author: "Collin Harris, Rita Wortham, Candace Rheaume, Madison Huff",
//   },
//   {
//     question: "NCPRO is collecting KPI data for SFRF projects? Which measure type is NOT regular type of KPI measures?",
//     choices: ["Finance Measure", "Output Measure", "Outcome Measure", "Tracking Measure"],
//     answer: "A",
//     explanation: "The regular KPI measure types are: Tracking Measure; Output Measure; Outcome Measure.",
//     author: "Yongjun Lei",
//   },
//   {
//     question: "How many films and television programs have been filmed in NC?",
//     choices: ["0-1000", "1001-2000", "2001-3000", "3001-4000"],
//     answer: "D",
//     explanation:
//       "Some 3,000 films and television programs have been made here, beginning in the early 1900s with silent movies that were shot in western North Carolina.. Some well known examples include Forrest Gump, Last of the Mohicans, The Color Purple, Dirty Dancing, Last of the Mohicans, and The Hunger Games",
//     author: "Natalie Garrett",
//   },
// ];
